import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Main from'../components/Main'
import About from'../components/About'
import Divbar from '../components/Divbar'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'

 
export default function Home() {
  return (
    <div>
      <Head>
        <title>yalauddin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Navbar></Navbar>
    <Main></Main>
    <About></About>
    <Skills></Skills>
    <Projects></Projects>
    <Contact></Contact>
    </div>
  )
}
