import Head from "next/head"
import Navbar from "../components/Navbar"
import OsmMap from "../components/OsmMap"
const osmapp = () => {
    return  <div>

    <Head>
    <title>Closest Building App | yalauddin</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

    <Navbar>
    </Navbar>
    
    <OsmMap></OsmMap>
  </div>

}

export default osmapp