import Head from "next/head"
import Navbar from "../components/Navbar"
import SmartPassword from "../components/SmartPassword"
const passwordmanager = () => {
    return  <div>

    <Head>
    <title>SmartPassword | yalauddin</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

    <Navbar>
    </Navbar>
    
    <SmartPassword></SmartPassword>
  </div>

}

export default passwordmanager