import Head from "next/head"
import Navbar from "../components/Navbar"
import Portfolio from "../components/Portfolio"
const yalauddin = () => {
    return  <div>

    <Head>
    <title>yalauddin.com | yalauddin</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

    <Navbar>
    </Navbar>

    <Portfolio></Portfolio>
    
  </div>

}

export default yalauddin